name: Build iOS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build iOS
        run: |
          xcodebuild \
          -project iosApp/iosApp.xcodeproj \
          -scheme iosApp \
          -sdk iphonesimulator \
          -configuration Release \
          build
